### ISSUE TITLE
Error handling for the Agent

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/identus#17]
Although PRISM already has some errors defined and returned by our Cloud Agent RestAPI calls, we do not have any mechanism to handle and report errors when they are happening during record processing or sending/receiving DIDComm messages. It is required to implement a mechanism of error handling for Cloud Agent to log, update records in the database, and report errors in the right way.

- [ ] hyperledger/identus-edge-agent-sdk-ts/issues/308

**Comment by FabioPinheiro** [comment]
@elribonazo this is done no?

**Comment by FabioPinheiro** [comment]
I'm in favor of close this ticket. But feel free to open it again
