### ISSUE TITLE
Identus as first-class citizen in Hyperledger's Discord

### ISSUE THREAD

**Issue by FabioPinheiro** [hyperledger/identus#40]
The Hyperledger's Discord seems to still no have Identus in some place as the other projects.
For example: 
When we enter the Discord for the first time. There are some questions to determine the channels that you probably want to see. But Identus is missing on the "Customization Questions".

Also, would be nice to have under Identus group of channels, one just for questions just related with the mediator. So I can keep easily keep an eye on it.

**Comment by FayyaadhAdams** [comment]
@FabioPinheiro we currently do have an Identus group of channels 
<img width="241" alt="image" src="https://github.com/user-attachments/assets/e6ae0836-1e25-432b-b51c-dd4a8c64a59c">

Are you not seeing them? There is a specific mediator channel as well https://discord.com/channels/905194001349627914/1252629675943919679

As for the Identus questions, this will be added by @ryjones pretty soon.

**Comment by ryjones** [comment]
I've added Identus and Web3J to the onboarding questions.

**Comment by essbante-io** [comment]
Thanks @FayyaadhAdams and @ryjones. And @FabioPinheiro for the suggestion.
