### ISSUE TITLE
Universal Resolver for Prism DIDs

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/identus#46]
We recently contributed to the universal resolver repository to integrate the prism did resolver in mainnet, using one community maintained service. 

Changes can be found in here and dids that are in mainnet can be resolved from there too
https://dev.uniresolver.io/

**Comment by mixmix** [comment]
Needs more detail

**Comment by elribonazo** [comment]
I updated the original description and will set this task as completed @FabioPinheiro is the one which contributed to it through https://github.com/decentralized-identity/universal-resolver/pull/440
