### ISSUE TITLE
Improve Infrastructure provisioning

### ISSUE THREAD

**Issue by elribonazo** [hyperledger/identus#76]
### Short Description

Improve the infrastructure provisioning by reducing the amount of services that are bundled by default + making those easier to configure and not require any specific SH configuration script. On top of that we also aim to make everything deployable from a single docker image and not require too many images.

### Value statement

Main goal behind this EPIC is to make our services easier to configure and maintain over time. For existing users, this will improve code maintenance and reduce the time spent on configuring the services and for our new users this will make it extremely easier to kick-off your project in Identus ecosystem. We mainly aim to reduce friction when it comes to configuring the services and get everything configured to start developing code.

### Components

[Cloud Agent](https://github.com/hyperledger/identus-cloud-agent)

### Team members

@hyperledger/identus

### Architect

@hyperledger/identus-maintainers 

### QA Member

@hyperledger/identus-maintainers 

### Owner

@hyperledger/identus-maintainers

**Comment by FabioPinheiro** [comment]
I think with this https://github.com/hyperledger/identus/pull/85 it should be easy enough for anyone with zero knowledge to start.

**Comment by amagyar-iohk** [comment]
@FabioPinheiro @elribonazo when running locally there's the docker network issue because SDK runs outside docker and is not able to communicate to the mediator

**Comment by amagyar-iohk** [comment]
@FabioPinheiro I noticed this line has a typo https://github.com/hyperledger/identus/blob/main/identus-docker/docker-compose.yaml#L58

**Comment by amagyar-iohk** [comment]
Working as expected
